# Generated by Django 4.1.2 on 2022-10-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helicopters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helicopter',
            old_name='passengers',
            new_name='amount_of_passengers',
        ),
    ]
